name: ghelobytes
description: hack of all trades. master of none. really
meta_description: "All about being ghelo."

markdown: redcarpet
pygments: true
logo: true
paginate: 15

baseurl:        'http://ghelobytes.github.io/'

# Details for the RSS feed generator
url:            'http://ghelobytes.github.io'
author:         'Angelo Arboleda'
